### ISSUE TITLE
Error when running the example

### ISSUE THREAD

**Issue by jestintab** [der-david/vlc-renode#1]
I'm getting error when running the example code. please help me to solve it. 

`$ node vlc.js --use_strict --harmony
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn vlc ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
`

**Comment by der-david** [comment]
Please make sure that the vlc executable is runnable from your respective working directory. Open a shell in that directory and try to launch vlc manually. You can also try an absolute path to the executable if you do not want to add it to your `PATH` (Windows) environment variable (or the respective equivalent of other OS's). 
Depending on your OS and vlc-copy you can try to use `cvlc` instead of `vlc`.
